### ISSUE TITLE
Join Domain with AWS Active Directory does not appear to work

### ISSUE THREAD

**Issue by HighPoint** [awsdocs/amazon-s3-file-gateway-user-guide#1]
Hi, 

The join domain for the S3 file gateway with an AWS Managed Microsoft Active Directory does not appear to work. I also tried manually joining the domain with the AWS SDK for Python (Boto3). I SSH into the Linux instance but could not exit the shell program. Any guidance would be helpful.

Best,

Mark

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
